### ISSUE TITLE
Opera 0.6.4 deployment issue

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/xopera-opera#13] opened 2021-01-18 08:35 UTC
Hi,
I am getting the following error log for every csar I am trying to deploy. Csars are constructed based on the latest radon-particles repository.
`TOSCA-Metadata/TOSCA.meta: Missing required meta entry: TOSCA-Meta-File-Version`

**Comment by cankarm** [comment] 2021-01-18 09:21
Just out of my curiosity - if you unzip CSAR, is there TOSCA.meta file? Or any ".meta" file that you can find there?

**Comment by anzoman** [comment] 2021-01-18 11:16
It seems that `TOSCA.meta` file is present but within it the required field `TOSCA-Meta-File-Version: 1.1` is missing.

@AlexSpart can you supply the CSAR file here?

**Comment by AlexSpart** [comment] 2021-01-18 11:38
There is a TOSCA.meta file where `TOSCA-Meta-Version: 1.0` is defined.
Github doesn't like the csar file type to supply it here, but I believe you can reproduce it with any csar exported from the IDE.

**Comment by cankarm** [comment] 2021-01-18 11:41
OK, thanks. We will triage this issue.

**Comment by anzoman** [comment] 2021-01-18 11:53
@AlexSpart from the [TOSCA YAML v1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969474):

> Due to the changes to the TOSCA.meta file compared to TOSCA 1.2 the TOSCA-Meta-File-Version keyword listed in block_0 of the the meta-file is required to denote version 1.1.

So, I believe that the `TOSCA-Meta-File-Version` should be set to `1.1` (which opera accepts) instead of `1.0`.

**Comment by sstanovnik** [comment] 2021-01-18 11:56
This is notabug as far as TOSCA is concerned, and notaregression as far as `opera~0.x.x` is concerned. 

The correct and mandatory entry for the version is `TOSCA-Meta-File-Version`, which must be set to `1.1`. This has been the case since 1.0 and persists through 1.3 (with 1.3 changing the value from `1.0` to `1.1`. `TOSCA-Meta-Version` is not a valid key for the meta file. However, the [TOSCA 1.0 spec](https://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.pdf) does include it in an example on line 3101. This example is not consistent with the standard, which prescribes `TOSCA-Meta-File-Version` on line 2962.

Opera has been allowing invalid CSARs with `TOSCA-Meta-Version` until `0.6.4`. With this version, we adhere to the spec more strictly, which means we fail with the exact error you found.

As far as I know, the only leftover difference between what opera parses and what the TOSCA standards specify is that opera treats `TOSCA.meta` as a YAML file, which it is not. Most valid meta files will be correctly parsed, however multiline strings are unsupported.

**Comment by AlexSpart** [comment] 2021-01-18 12:12
It makes sense. Are @miwurster or @v-yussupov already aware of this issue?

**Comment by miwurster** [comment] 2021-01-18 13:25
Thanks for the pointer @AlexSpart.

PR for RADON GMT is already open: https://github.com/eclipse/winery/pull/551

**Comment by anzoman** [comment] 2021-06-30 07:56
The linked PR has been merged and I'm closing this issue. If the problem still persists (with the [latest](https://pypi.org/project/opera/) version of opera), please reopen this issue.

**Closed as completed by anzoman** 2021-06-30 07:56 UTC
Labels: BUG
