### ISSUE TITLE
Input passing into a newly defined relationship type

### ISSUE THREAD

**Issue by sydkbc** [radon-h2020/xopera-opera#11] opened 2020-10-12 09:12 UTC
I have the following newly defined relationship type (for Monitoring nodes purposes):

_**tosca_definitions_version: tosca_simple_yaml_1_3

relationship_types:
  radon.relationships.IsMonitoredBy:
    derived_from: tosca.relationships.ConnectsTo
    metadata:
      targetNamespace: "radon.relationships"
      abstract: "false"
      final: "false"
    interfaces:
      Configure:
        type: tosca.interfaces.relationship.Configure
        inputs:
          monitored_function:
            type: string
            required: true
            default: { get_property: [ SOURCE, name ] }
          pushgateway_ip:
            type: string
            required: true
            default: { get_attribute: [ TARGET, pushgateway_ip ] }
          user_email:
            type: string
            required: true
            default: { get_property: [ TARGET, user_email ] }
          grafana_ip: 
            type: string
            required: true
            default: { get_property: [ TARGET, grafana_ip ] }
          service_account_file:
            type: string
            required: true
            default: "/tmp/service_account.json"
        operations:
          post_configure_source:
            implementation:
              primary: grafana-injection
              timeout: 30**_

The service_account_file input can only be assigned to a value that is defined as an input (get_input: service_account_file)
When I try to read the value like that I get an error notifying that:

Relationship does not have topology parameter.

Any ideas?

**Comment by cankarm** [comment] 2020-10-15 12:18
Hi @sydkbc,
thanks for pointing this out. 

Do you use this relationship in the topology_template and how?

Maybe @anzoman  can spot the issue here.

**Comment by anzoman** [comment] 2020-10-15 12:47
@cankarm I am asking your questions myself. @sydkbc it would be helpful if you provide full TOSCA template/CSAR.

**Comment by sydkbc** [comment] 2020-10-16 07:43
@anzoman I ll provide both the TOSCA template and a snapshot of the GMT topology.

[Monitoring.zip](https://github.com/radon-h2020/xopera-opera/files/5389972/Monitoring.zip)
![GCP Function Monitoring Service Template](https://user-images.githubusercontent.com/36516781/96227160-5fb5d900-0f9c-11eb-8c39-788da25987f0.png)

The relationship type is the IsMonitoredBy relationship.

**Comment by anzoman** [comment] 2020-10-20 07:45
@sydkbc thanks for providing the CSAR and the snapshot.

I've tried to extract and deploy your CSAR (with opera [0.6.2.dev7 version](https://test.pypi.org/project/opera/0.6.2.dev7/)) and I get the following output:

```console
(.venv) anzoman@ubuntu:~/Desktop/xopera-opera/Monitoring/Monitoring$ opera deploy _definitions/steIgeneral__Monitoring-Examples_w1-wip1.tosca 
[Worker_0]   Deploying AwsPlatform_0_0
[Worker_0]     Executing configure on AwsPlatform_0_0
[Worker_0]   Deployment of AwsPlatform_0_0 complete
[Worker_0]   Deploying EC2_0_0
[Worker_0]     Executing create on EC2_0_0
[Worker_0]   Deployment of EC2_0_0 complete
[Worker_0]   Deploying DockerEngine_0_0
[Worker_0]     Executing configure on DockerEngine_0_0
[Worker_0]   Deployment of DockerEngine_0_0 complete
[Worker_0]   Deploying PushGateway_0_0
[Worker_0]     Executing create on PushGateway_0_0
[Worker_0]     Executing configure on PushGateway_0_0
[Worker_0]   Deployment of PushGateway_0_0 complete
[Worker_0]   Deploying GoogleCloudPlatform_0_0
[Worker_0]     Executing create on GoogleCloudPlatform_0_0
[Worker_0]   Deployment of GoogleCloudPlatform_0_0 complete
[Worker_0]   Deploying GoogleCloudBucket_0_0
[Worker_0]     Executing create on GoogleCloudBucket_0_0
Error processing node GoogleCloudBucket_0_0: Cannot use an unset value: service_account_file
```
So the problem is in the input called `service_account_file`. I had a look at your entry point TOSCA file (`/Monitoring/_definitions/steIgeneral__Monitoring-Examples_w1-wip1.tosca`) and I see that you defined the `service_account_file` input at the beginning of the `topology_template` section. However, the issue is that the value for the input has not been set anywhere and when you try to read it with the `get_input` TOSCA function you get an error. Now what you can do to prevent this is that you can set a default value for your input like this: 

```yaml
topology_template:
  inputs:
    service_account_file:
      type: string
      default: "/tmp/service_account.json"
```

And then when you start the deployment you can override the value by supplying YAML inputs file (it's just an ordinary YAML file with key-value pairs like `service_account_file: /tmp/account.json`) to the opera orchestrator like this:

```console 
opera init Monitoring.zip
opera deploy -i inputs.yaml 
```

I tried to deploy with a default `service_account_file` input value and I get this output:

```console
(.venv) anzoman@ubuntu:~/Desktop/xopera-opera/Monitoring/Monitoring$ opera deploy _definitions/steIgeneral__Monitoring-Examples_w1-wip1.tosca 
[Worker_0]   Deploying AwsPlatform_0_0
[Worker_0]     Executing configure on AwsPlatform_0_0
[Worker_0]   Deployment of AwsPlatform_0_0 complete
[Worker_0]   Deploying EC2_0_0
[Worker_0]     Executing create on EC2_0_0
[Worker_0]   Deployment of EC2_0_0 complete
[Worker_0]   Deploying DockerEngine_0_0
[Worker_0]     Executing configure on DockerEngine_0_0
[Worker_0]   Deployment of DockerEngine_0_0 complete
[Worker_0]   Deploying PushGateway_0_0
[Worker_0]     Executing create on PushGateway_0_0
[Worker_0]     Executing configure on PushGateway_0_0
[Worker_0]   Deployment of PushGateway_0_0 complete
[Worker_0]   Deploying GoogleCloudPlatform_0_0
[Worker_0]     Executing create on GoogleCloudPlatform_0_0
[Worker_0]   Deployment of GoogleCloudPlatform_0_0 complete
[Worker_0]   Deploying GoogleCloudBucket_0_0
[Worker_0]     Executing create on GoogleCloudBucket_0_0
[Worker_0]   Deployment of GoogleCloudBucket_0_0 complete
[Worker_0]   Deploying GoogleCloudBucket_1_0
[Worker_0]     Executing create on GoogleCloudBucket_1_0
[Worker_0]   Deployment of GoogleCloudBucket_1_0 complete
[Worker_0]   Deploying GoogleCloudBucketTriggeredFunction_0_0
[Worker_0]     Executing create on GoogleCloudBucketTriggeredFunction_0_0
[Worker_0]     Executing post_configure_source on GoogleCloudBucketTriggeredFunction_0_0--PushGateway_0_0
[Worker_0]   Deployment of GoogleCloudBucketTriggeredFunction_0_0 complete
```

So, the deployment now succeeds. Will this solve your issues?

**Comment by sydkbc** [comment] 2020-10-21 14:12
Hello @anzoman 
First of all thanks for the clarifications.

I did what you proposed and I still get the issue. In detail:

In the service template:
![image](https://user-images.githubusercontent.com/36516781/96731824-5a9fc200-13c0-11eb-86fc-4ce2e848360f.png)

In the IsMonitoredBy relationship:
![image](https://user-images.githubusercontent.com/36516781/96731898-7014ec00-13c0-11eb-9d14-73367395639b.png)

The error persists as follows:

![image](https://user-images.githubusercontent.com/36516781/96731956-80c56200-13c0-11eb-8a30-750e57bfb659.png)

**Comment by sydkbc** [comment] 2020-10-21 14:37
What is also a bit weird is that I don't get your initial error... ever.
Error processing node GoogleCloudBucket_0_0: Cannot use an unset value: service_account_file

In my case from point 0 the error reported is:
Error processing node GoogleCloudBucketTriggeredFunction_0_0: 'Relationship' object has no attribute 'topology'

**Comment by anzoman** [comment] 2020-10-22 08:20
Hmm I see, this is strange. And have you tried to deploy the CSAR with opera [0.6.2.dev7 version](https://test.pypi.org/project/opera/0.6.2.dev7/) which is a development version?

**Comment by sydkbc** [comment] 2020-10-22 09:36
I tried that as well but the error persists:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/36516781/96853474-11547e80-1463-11eb-8753-cb16483810a6.png">

I don't know if this is something relevant but I am using an Apple Mac as a machine. Just FYI...

**Comment by anzoman** [comment] 2020-10-22 10:37
Thanks for your info and I think I found the problem.

So, my deployment worked because I had also set the default value for the `service_account_file` in `IsMonitoredBy` relationship type like this:

![image](https://user-images.githubusercontent.com/41727816/96860262-d5211e00-1462-11eb-8627-72c340e554f5.png)

I think that you have found a bug in opera that prevents getting input values from relationships. Thank you for that! In the mean time before this gets fixed, you can try to deploy like me, using only the default input value in the relationship.

**Comment by anzoman** [comment] 2020-10-22 11:50
I created a new issue on opera to track that problem: https://github.com/xlab-si/xopera-opera/issues/117

**Comment by sydkbc** [comment] 2020-10-22 12:25
Great!
Thanks for the help

**Comment by anzoman** [comment] 2021-01-18 12:35
xlab-si#117 was merged. @cankarm I believe that the issue here was resolved.

**Comment by cankarm** [comment] 2021-01-18 13:18
Great, thanks for pointing that out, @anzoman. I'm closing this.

**Closed as completed by cankarm** 2021-01-18 13:18 UTC
